### ISSUE TITLE
Some Type system improvements

### ISSUE THREAD

**Issue by HalosGhost** [ark-lang/docs#2]
## Type inference

At the moment, type inference prefers doubles always rather than floats (for a decent reason). However, perhaps a better system would be to offer an explicit literal for floats so that a user can still force a float with type inference. In many C-family languages, this is accomplished by adding a `f` to the end of the would-otherwise-be-double literal:

`1.2` ← `double`
`1.2f` ← `float`
## Naming convention

At the moment, you have opted for `{i,u}{8,16,32,64,128}`. I would recommend you replace the `i` with `s` (for `signed`). If we are to be explicit, we might as well be as explicit as possible.
## Arbitrarily-Sized, Fixed-width Integers

Perhaps one of the coolest features of LLVM, in my humble opinion, is that integer arithmetic is well-defined for integers of _any_ bitwidth. And, that arbitrarily-sized fixed-width integers are openly exposed. So, for example, in LLVM IR, you could write the following:

```
%var = alloca i9
store i9 511, i9* %var
```

It would work! `%var` is a nine-bit integer! Admittedly, these fancypants integers are generally converted to system-native types during the compilation process, but it does allow for more specific compile-time type-checking. Since these are exposed in LLVM IR itself, inclusion of them into the language would not necessarily be so difficult (on the condition that it only works in the LLVM backend).

**Comment by felixangell** [comment]
Hey! I think the first point is already implemented, although a recent issue @MovingtoMars suggested to remove these, so perhaps he's gone through with that change.
As for `s` over `i`, I actually quite like this, and think it's a good idea. 
And the last point, I'm not sure. If you're suggesting we allow for different sized integers to be defined by the programmer... then maybe? I don't know. :)

**Comment by MovingtoMars** [comment]
So, for the thing about removing `f`, `d` and `q` suffixes, I just haven't implemented it yet.

I kinda like the `s` and `u` change.

Allowing arbitary-width integers is not a good idea though. 
- easy to make typos and get the wrong type
- anything other than exponents of 2 will have terrible performance

**Comment by felixangell** [comment]
@MovingtoMars I don't think you should remove them, since it's a lot easier to type `f` and `d` than cast it to a float or double, plus the suffixes are pretty well recognised across languages.
And I agree with the last point. But I think `s` over `i` a good idea.

**Comment by MovingtoMars** [comment]
@felixangell that's what I meant, I'm not removing them, I just haven't added them to the compiler yet.

**Comment by HalosGhost** [comment]
The performance difference in arbitrarily-sized fixed-width integers should not be dramatically worse for anything (unless you go way beyond a 128-width integer since that's not natively supported by any architecture targeted by LLVM afaik; and even then, they would only be about as inefficient/slow as emulating 64-bit arithmetic is on a 32-bit machine—not _that_ slow). Note, they are _not_ BigInts, they are fixed-width; you just get to decide how many bits wide to make it. As for it being easy to typo, I am not actually convinced that that's true. Why is it easier to typo i10 than i16?

Also, I forgot to mention another improvement I would like to recommend:

## (Nearly-)Arbitrary Radix literals

At the moment, ark supports `0b`, `0o` and `0x` for binary, octal and hexadecimal (respectively) prefixes for integer literals. Some other languages have seen fit to fix this by including a simple, universal prefix which declares the radix of the type using a decimal natural. This prefix takes the form of the decimal natural representation of the radix followed by a `#` followed by the integer. For example:

```
2#10010101; // An integer literal in base-2 (binary) with the value of 95 (in hexadecimal)
8#72; // base-8 (octal) representation of the decimal value 58
16#ff; // base-16 (hex) representation of the decimal value 255
```

In addition to the most common radices, these languages often allow for (almost) any other decimal natural number to be used as the radix so that you can use literals in whatever radix you want. The languages which implement this style often disallow radices above 31 (or near it) because base32 and base64 have preset standard representations which do not meld well with previous radices (the notion that in each successive radix, you simply add a symbol rather than completely change the value of certain symbols). This also allows for something interesting like `1#11111` for what is essentially tallying (that would be the decimal value `5`). This standardizes the syntax for integer literals in different radices and offers more flexibility to programmers.

**Comment by felixangell** [comment]
Interesting, however I don't see a very compelling use for these features. Good call on `s` over `i`, though! :smile: 

@ark-lang/owners 
Anyone else have any thoughts on this, or shall we close?

**Comment by HalosGhost** [comment]
While I'm sorry you don't see the merits of some of the other recommendations, I'm glad you found at least some of my suggestions helpful! Keep up the good work on Ark!

**Comment by raoulvdberge** [comment]
Since noone else has thoughts on this, I'll close the issue.
