### ISSUE TITLE
Add Travis CI auto-push on successful build to ark-lang/book.ark-lang.org.

### ISSUE THREAD

**Issue by ghost** [ark-lang/docs#7]
To ensure that all PRs to this repo are automagically built and pushed to the live website, I would suggest utilising Travis CI's [custom deployment options](http://docs.travis-ci.com/user/deployment/custom/#Git). Then, having the documentation be built would be merely a matter of pushing any source edits to this repo.

**Comment by felixangell** [comment]
Ohh yeah forgot about this, will setup some point.
